### ISSUE TITLE
Nesting parallel() calls results in TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by kumar303** [danielstjules/mocha.parallel#9]
I thought it would be a good idea to use `parallel()` for all definitions so that refactoring wouldn't accidentally introduce a call to `describe()`. A definition like this results in the following error:

````javascript
parallel('module', () => {
  parallel('someFunction', () => {
    it('does something...', () => {
      // ...
    });
  });
});
````

````
TypeError: Cannot read property 'then' of null
      at Context.<anonymous> (node_modules/mocha.parallel/index.js:104:28)
      at node_modules/mocha.parallel/index.js:270:20
      at tryCatcher (node_modules/mocha.parallel/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._resolveFromResolver (node_modules/mocha.parallel/node_modules/bluebird/js/main/promise.js:480:31)
      at new Promise (node_modules/mocha.parallel/node_modules/bluebird/js/main/promise.js:70:37)
      at node_modules/mocha.parallel/index.js:259:12
      at spec.getPromise (node_modules/mocha.parallel/index.js:173:43)
      at bound (domain.js:280:14)
      at runBound (domain.js:293:12)
      at tryCatcher (node_modules/mocha.parallel/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (node_modules/mocha.parallel/node_modules/bluebird/js/main/promise.js:507:31)
      at Promise._settlePromiseAt (node_modules/mocha.parallel/node_modules/bluebird/js/main/promise.js:581:18)
      at Promise._settlePromises (node_modules/mocha.parallel/node_modules/bluebird/js/main/promise.js:697:14)
      at Async._drainQueue (node_modules/mocha.parallel/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (node_modules/mocha.parallel/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues [as _onImmediate] (node_modules/mocha.parallel/node_modules/bluebird/js/main/async.js:15:14)
````

Using `describe()` at the top level fixed it:

````javascript
describe('module', () => {
  parallel('someFunction', () => {
      // ...
  });
});
````
I guess it's not really necessary to put `parallel()` at the top level. Maybe this could just be documented explicitly?

**Comment by danielstjules** [comment]
Thanks for the issues! In the overview, it mentions:

> Supports hooks, pending or skipped specs/suites via parallel.skip() and it.skip(), but not nested suites

Nested suites meaning you can't nest `describe` or `parallel` calls in `parallel`.
